---
title: "Calendar"
---


The calendar below lists the tentative course topics. The dates listed are subject to change at the instructor's discretion.

As part of the course, there are several articles, papers and technical reports that you will need to read during the semester. Most of the articles themselves are accessible through the [University of Minnesota library website](http://www.lib.umn.edu). In order to access the full text of some of the articles, you will need to log in using your University x500 username and password. More detailed information, including references or links to specific readings, are linked under the day's "Reading".

<br /><br />


<br />


<table class="table">

<thead>
<tr>
<th style="width:10%;text-align:center"></th>
<th style="width:10%;">Date</th>
<th style="width:10%;text-align:center">Reading</th>
<th style="width:50%;">Topic</th>
<th style="width:10%;text-align:center">Notes</th>
<th style="width:10%;text-align:center">Script</th>
</tr>
</thead>

<!-- <thead> -->
<!-- <tr> -->
<!-- <th style="width:10%;text-align:center"></th> -->
<!-- <th style="width:10%;">T/R</th> -->
<!-- <th style="width:10%;">M/W</th> -->
<!-- <th style="width:10%;text-align:center">Reading</th> -->
<!-- <th style="width:40%;">Topic</th> -->
<!-- <th style="width:10%;text-align:center">Notes</th> -->
<!-- <th style="width:10%;text-align:center">Script</th> -->
<!-- </tr> -->
<!-- </thead> -->

<tbody>

<!-- <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Notes and Script file updated 09-24-2019]*</span></td> -->



<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<!-- <td>Sept. 03</td> -->
<td>Sept. 06</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/00-welcome-to-8251.html)
</td>
<td>Welcome to EPsy 8251</td>
<td align="center" style="vertical-align:middle;">
  <span class="fas fa-link" style="color: #f1f1f1; font-size: 20px;"></span>
</td>
<td align="center" style="vertical-align:middle;">
  <span class="fa fa-code" style="color: #f1f1f1; font-size: 20px;"></span>
</td>
</tr>


<!-- Unit 01: INTRODUCTION TO STATISTICAL COMPUTING -->

<tr>
<td colspan="7"><b>Unit 01: Introduction to Statistical Computing</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 05</td> -->
<td>Sept. 11</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/01-01-introduction-to-r-and-rstudio.html)
</td>
<td>Introduction to R and RStudio</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](worksheets/worksheet-01-01-using-R.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/01-01-introduction-to-r.R)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 10</td> -->
<td>Sept. 13</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/01-04-data-wrangling-with-dplyr.html)
</td>
<td>Data Wrangling with dplyr</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](worksheets/worksheet-01-04-learning-dplyr.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/01-04-data-wrangling-with-dplyr.R)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 12</td> -->
<td>Sept. 18</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/01-05-plotting-with-ggplot2)
</td>
<td>Plotting with ggplot2</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](worksheets/worksheet-01-05-ggplot2.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/01-05-plotting-with-ggplot2.R)
</td>
</tr>


<!-- Unit 02: REGRESSION BASICS -->

<tr>
<td colspan="7"><b>Unit 02: Regression Basics</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 17</td> -->
<td>Sept. 20</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/02-01-simple-linear-regression-description.html)
</td>
<td style="vertical-align:middle;" rowspan="2">Simple Linear Regression: Description
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/02-01-simple-regression-description.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/02-01-simple-linear-regression-description.R)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 19</td> -->
<td>Sept. 25</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 24</td> -->
<td>Sept. 27</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/02-02-ols-estimation.html)
</td>
<td style="vertical-align:middle;">Ordinary Least Squares (OLS) Estimation
<td align="center" style="vertical-align:middle;">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/02-02-ols-estimation.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/02-02-ols-estimation.R)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 26</td> -->
<td>Oct. 02</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/02-03-correlation-and-standardized-regression.html)
</td>
<td style="vertical-align:middle;">Correlation (and Standardized Regression)</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/02-03-correlation.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/02-03-correlation-and-standardized-regression.R)
</td>
</tr>

<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <td>Oct. 01</td> --> 
<!-- <td>Oct. 04</td> -->
<!-- </tr> -->


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 03</td> -->
<td>Oct. 04</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/02-04-coefficient-level-inference.html)
</td>
<td style="vertical-align:middle;" rowspan="2">Coefficient-Level Inference</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/02-04-coefficient-level-inference.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/02-04-coefficient-level-inference.R)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 08</td> -->
<td>Oct. 09</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 10</td> -->
<td>Oct. 11</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/02-05-model-level-inference.html)
</td>
<td style="vertical-align:middle;" rowspan="2">Model-Level Inference</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/02-05-model-level-inference.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/02-05-model-level-inference.R)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 15</td> -->
<td>Oct. 16</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 24</td> -->
<td>Oct. 18</td>
<td align="center" style="vertical-align:middle;">
  <!-- <a href="preparation.html#control"> -->
  <!--   <span class="fa fa-book" style="font-size: 20px;"></span> -->
  <!-- </a> -->
</td>
<td style="vertical-align:middle;">*NO CLASS&mdash;Mental Health Day*
<td align="center" style="vertical-align:middle;"></td>
<td align="center" style="vertical-align:middle;"></td>
</tr>

<!-- Unit 03: DEEPER UNDERSTANDING -->


<tr>
<td colspan="7"><b>Unit 03: Deeper Understanding</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 17</td> -->
<td>Oct. 23</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/03-01-introduction-to-multiple-linear-regression.html)
</td>
<td style="vertical-align:middle;" rowspan="2">Introduction to Multiple Linear Regression</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/03-01-intro-to-multiple-regression.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/03-01-introduction-to-multiple-regression.R)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 22</td> -->
<td>Oct. 25</td>
</tr>

<!-- UNDERSTANDING STATISTICAL CONTROL -->

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 24</td> -->
<td>Oct. 30</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/03-02-understanding-statistical-control.html)
</td>
<td style="vertical-align:middle;" rowspan="2">Understanding Statistical Control</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/03-02-understanding-statistical-control.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/03-02-understanding-statistical-control.R)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 29</td> -->
<td>Nov. 01</td>
</tr>


<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <!-- <td>Sept. 24</td> --> 
<!-- <td>Nov. 07</td> 
<!-- <td align="center" style="vertical-align:middle;"> -->
<!--   <!-- <a href="preparation.html#control"> --> 
<!--   <!--   <span class="fa fa-book" style="font-size: 20px;"></span> -->
<!--   <!-- </a> --> 
<!-- </td> -->
<!-- <td style="vertical-align:middle;">*NO CLASS&mdash;Mental Health Day --- Andy at a conference* -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- </tr> -->

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Oct. 31</td> -->
<td>Nov. 06</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/03-03-distributional-assumptions-underlying-the-regression-model.html)
</td>
<td style="vertical-align:middle;" rowspan="2">Assumptions of the Regression Model</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/03-03-assumptions.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/03-03-distributional-assumptions-underlying-the-regression-model.R)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Nov. 05</td> -->
<td>Nov. 08</td>
</tr>





<!-- Unit 04: EXTENDING THE REGRESSION MODEL -->

<tr>
<td colspan="7"><b>Unit 04: Extending the Regression Model</b></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Nov. 07</td> -->
<td>Nov. 13</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/04-01-dichotomous-categorical-predictors.html)
</td>
<td style="vertical-align:middle;" rowspan="2">Dummy Coding Categorical Predictors</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/04-01-dichotomous-predictors.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/04-01-dichotomous-categorical-predictors.R)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Nov. 12</td> -->
<td>Nov. 15</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Nov. 19</td> -->
<td>Nov. 20</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/04-02-polychotomous-categorical-predictors.html)
</td>
<td style="vertical-align:middle;">Polychotomous Categorical Predictors</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/04-02-polychotomous-predictors.html)
</td>
<td align="center" style="vertical-align:middle;">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/04-02-polychotomous-categorical-predictors.R)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Sept. 24</td> -->
<td>Nov. 22</td>
<td align="center" style="vertical-align:middle;">
  <!-- <a href="preparation.html#control"> -->
  <!--   <span class="fa fa-book" style="font-size: 20px;"></span> -->
  <!-- </a> -->
</td>
<td style="vertical-align:middle;">*NO CLASS&mdash;Mental Health Day*
<td align="center" style="vertical-align:middle;"></td>
<td align="center" style="vertical-align:middle;"></td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Nov. 19</td> -->
<td>Nov. 27</td>
<td align="center" style="vertical-align:middle;"  rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/04-02-polychotomous-categorical-predictors.html)
</td>
<td style="vertical-align:middle;"  rowspan="2">Polychotomous Categorical Predictors</td>
<td align="center" style="vertical-align:middle;"  rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/04-02-polychotomous-predictors.html)
</td>
<td align="center" style="vertical-align:middle;"  rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/04-02-polychotomous-categorical-predictors.R)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Nov. 05</td> -->
<td>Nov. 29</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Nov. 26</td> -->
<td>Dec. 04</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/04-03-introduction-to-interaction-effects.html)
</td>
<td style="vertical-align:middle;" rowspan="2">Introduction to Interaction Effects</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/04-03-interaction-effects.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/04-03-introduction-to-interaction-effects.R)
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Dec. 03</td> -->
<td>Dec. 06</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<!-- <td>Dec. 09</td> -->
<td>Dec. 11</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-book" style="font-size: 20px;"></span>](readings/04-04-more-interaction-effects.html)
</td>
<td style="vertical-align:middle;" rowspan="2">More Interaction Effects</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fas fa-link" style="font-size: 20px;"></span>](https://zief0002.github.io/modeling/04-04-more-interaction-effects.html)
</td>
<td align="center" style="vertical-align:middle;" rowspan="2">
  [<span class="fa fa-code" style="font-size: 20px;"></span>](scripts/04-04-more-interaction-effects.R)
</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;"></td>
<td>Dec. 13</td>
</tr>


<!-- <tr> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <td>Dec. 14</td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <td style="vertical-align:middle;">TBA</td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- <td align="center" style="vertical-align:middle;"></td> -->
<!-- </tr> -->

</tbody>
</table>    


